homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

post:
    path:     /post/{id}
    defaults: { _controller: AppBundle:Post:index }

about:
    path:     /about
    defaults: { _controller: AppBundle:About:index }

contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:index }


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
